site_name: Abanoub Ehab
theme:
  custom_dir: overrides
  name: material
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  features:
      - navigation.tabs
      - navigation.top


  hide:
    - navigation
    - toc


extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/abanoubehabmalak/

    - icon: fontawesome/brands/github 
      link: https://github.com/AbanoubEhab

    - icon: fontawesome/brands/facebook 
      link: https://www.facebook.com/abanoub.ehab.malak

    - icon: fontawesome/brands/discord 
      link: https://discordapp.com/users/989272289289863198



