site_name: Abanoub Ehab Malak - System Administrator
site_description: System Administrator specializing in multi-site Linux infrastructure, virtualization (Proxmox VE), and self-hosted solutions in Cairo, Egypt.
site_url: https://abanoubehab.github.io
repo_url: https://github.com/AbanoubEhab/AbanoubEhab.github.io
theme:
  
  logo: assets/logo.png
  favicon: assets/logo.png
  name: material
  palette:

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black


  features:
      - navigation.tabs
      - navigation.top



markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - overrides/assets/javascripts/extra.js


extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/abanoubehabmalak/

    - icon: fontawesome/brands/github 
      link: https://github.com/AbanoubEhab
