site_name: Abanoub Ehab
theme:
  name: material
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/abanoubehabmalak/

    - icon: fontawesome/brands/github 
      link: https://github.com/AbanoubEhab
